### ISSUE TITLE
There's a bunch of screenshots committed in the repo

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Benchmarks#1]
Also cache files.

The sad part is that even if you remove them, they spam the git history forever and make cloning considerably longer than it should've been.

**Comment by psimyn** [comment]
newish repo with no forks. Just delete/recreate or rebase and force push?

**Comment by ashdnazg** [comment]
but that will mean that every existing local repo on people's machines will get crapped out when trying to pull.
